const THEMES = {
  Animals: [
    "DOG","CAT","HORSE","TIGER","LION","WOLF","FOX","BEAR","SHEEP","GOAT",
    "COW","PIG","MOUSE","RABBIT","DEER","MONKEY","APE","KOALA","PANDA","ZEBRA",
    "CAMEL","OTTER","SEAL","WHALE","DOLPHIN","SHARK","EAGLE","OWL","CROW","FALCON"
  ],

  Countries: [
    "FRANCE","SPAIN","ITALY","GERMANY","BELGIUM","SWEDEN","NORWAY","POLAND","GREECE","PORTUGAL",
    "CANADA","BRAZIL","ARGENTINA","CHILE","PERU","MEXICO","COLOMBIA","PANAMA","CUBA","JAMAICA",
    "JAPAN","CHINA","KOREA","INDIA","THAILAND","VIETNAM","NEPAL","BHUTAN","LAOS","MALAYSIA"
  ],

  Brands: [
    "APPLE","GOOGLE","MICROSOFT","AMAZON","META","TESLA","NIKE","ADIDAS","PUMA","REEBOK",
    "SONY","SAMSUNG","INTEL","NVIDIA","IBM","ORACLE","SPOTIFY","NETFLIX","DISNEY","UBER",
    "AIRBNB","PAYPAL","STRIPE","VISA","MASTERCARD","COCA","PEPSI","NESTLE","SHELL","TOTAL"
  ],

  Food: [
    "BREAD","CHEESE","BUTTER","YOGURT","PASTA","PIZZA","BURGER","STEAK","CHICKEN","BACON",
    "SALMON","TUNA","SHRIMP","RICE","NOODLE","SOUP","SALAD","TOMATO","ONION","GARLIC",
    "PEPPER","CARROT","POTATO","APPLE","BANANA","ORANGE","MANGO","GRAPE","LEMON","PEACH"
  ],

  Colors: [
    "BLACK","WHITE","GRAY","SILVER","GOLD","RED","BLUE","GREEN","YELLOW","ORANGE",
    "PURPLE","PINK","BROWN","BEIGE","IVORY","TEAL","CYAN","NAVY","MAROON","OLIVE",
    "LIME","MINT","CORAL","PEACH","PLUM","INDIGO","VIOLET","AMBER","BRONZE","COPPER"
  ],

  Jobs: [
    "DOCTOR","NURSE","TEACHER","LAWYER","ENGINEER","ARCHITECT","DESIGNER","WRITER","EDITOR","REPORTER",
    "CHEF","BAKER","COOK","FARMER","GARDENER","DRIVER","PILOT","CAPTAIN","SAILOR","FISHER",
    "ACTOR","SINGER","DANCER","PAINTER","SCULPTOR","PHOTOGRAPHER","DIRECTOR","PRODUCER","CAMERAMAN","EDITORIAL"
  ],

  Sports: [
    "SOCCER","RUGBY","TENNIS","CRICKET","HOCKEY","BASEBALL","BASKETBALL","VOLLEY","HANDBALL","BADMINTON",
    "GOLF","BOXING","WRESTLING","KARATE","JUDO","TAEKWONDO","SKIING","SNOWBOARD","SURFING","SWIMMING",
    "RUNNING","CYCLING","ROWING","SAILING","CLIMBING","HIKING","SKATING","FENCING","ARCHERY","SHOOTING"
  ],

  Music: [
    "ROCK","POP","JAZZ","BLUES","SOUL","FUNK","DISCO","TECHNO","HOUSE","TRANCE",
    "HIPHOP","RAP","REGGAE","SKA","METAL","PUNK","GRUNGE","INDIE","FOLK","COUNTRY",
    "CLASSICAL","OPERA","CHORAL","SYMPHONY","ORCHESTRA","PIANO","GUITAR","DRUMS","BASS","VIOLIN"
  ],

  Movies: [
    "ACTION","DRAMA","COMEDY","HORROR","THRILLER","ROMANCE","WESTERN","FANTASY","SCIENCE","FICTION",
    "ANIMATION","DOCUMENTARY","MYSTERY","CRIME","NOIR","MUSICAL","BIOPIC","HISTORY","WAR","SPORTS",
    "SUPERHERO","ADVENTURE","EPIC","SHORT","SERIES","SEQUEL","PREQUEL","REMAKE","SPINOFF","CAMEO"
  ],

  Technology: [
    "COMPUTER","LAPTOP","TABLET","PHONE","SERVER","NETWORK","CLOUD","DATABASE","ALGORITHM","SOFTWARE",
    "HARDWARE","BROWSER","WEBSITE","APP","SECURITY","ENCRYPTION","PASSWORD","LOGIN","ACCOUNT","PROFILE",
    "BACKUP","STORAGE","MEMORY","PROCESSOR","GPU","CPU","FIRMWARE","PROTOCOL","API","FRAMEWORK"
  ],

  Nature: [
    "FOREST","DESERT","MOUNTAIN","RIVER","OCEAN","LAKE","VALLEY","HILL","CLIFF","CANYON",
    "ISLAND","BEACH","GLACIER","VOLCANO","WATERFALL","STREAM","SWAMP","JUNGLE","RAINFOREST","SAVANNA",
    "PLAINS","MEADOW","FIELD","GARDEN","PARK","RESERVE","DELTA","REEF","COAST","SHORE"
  ],

  Emotions: [
    "HAPPY","SAD","ANGRY","EXCITED","NERVOUS","CALM","RELAXED","STRESSED","ANXIOUS","PROUD",
    "ASHAMED","CONFIDENT","HOPEFUL","FEARFUL","CURIOUS","BORED","TIRED","ENERGETIC","LONELY","LOVED",
    "JEALOUS","GRATEFUL","CONTENT","FRUSTRATED","SURPRISED","CONFUSED","INSPIRED","MOTIVATED","DEPRESSED","OPTIMISTIC"
  ],

  Vehicles: [
    "CAR","TRUCK","BUS","TRAIN","TRAM","SUBWAY","SCOOTER","MOTORBIKE","BICYCLE","SKATEBOARD",
    "AIRPLANE","HELICOPTER","GLIDER","JET","BOAT","SHIP","FERRY","SUBMARINE","YACHT","CANOE",
    "KAYAK","RAFT","TANK","TRACTOR","CRANE","FORKLIFT","VAN","SUV","SEDAN","COUPE"
  ],

  Clothing: [
    "SHIRT","PANTS","JEANS","SHORTS","SKIRT","DRESS","JACKET","COAT","HOODIE","SWEATER",
    "SOCKS","SHOES","BOOTS","SANDALS","SNEAKERS","HAT","CAP","BEANIE","SCARF","GLOVES",
    "BELT","TIE","SUIT","BLAZER","VEST","PYJAMAS","UNDERWEAR","BRIEFS","BOXERS","BATHROBE"
  ],

  BodyParts: [
    "HEAD","BRAIN","EYES","EARS","NOSE","MOUTH","TEETH","TONGUE","NECK","SHOULDERS",
    "ARMS","ELBOW","WRIST","HANDS","FINGERS","CHEST","BACK","SPINE","WAIST","HIPS",
    "LEGS","KNEE","ANKLE","FEET","TOES","HEART","LUNGS","LIVER","STOMACH","MUSCLES"
  ],

  Weather: [
    "SUNNY","CLOUDY","RAINY","STORMY","WINDY","FOGGY","SNOWY","ICY","HUMID","DRY",
    "HOT","COLD","WARM","COOL","FREEZING","BOILING","BREEZY","OVERCAST","DROUGHT","FLOOD",
    "THUNDER","LIGHTNING","HAIL","BLIZZARD","CYCLONE","HURRICANE","TORNADO","MONSOON","RAINBOW","MIST"
  ],

  Space: [
    "PLANET","STAR","GALAXY","NEBULA","COMET","ASTEROID","METEOR","ORBIT","GRAVITY","VACUUM",
    "SATELLITE","ROCKET","SPACESHIP","ASTRONAUT","COSMONAUT","TELESCOPE","OBSERVATORY","CONSTELLATION","UNIVERSE","COSMOS",
    "MARS","VENUS","EARTH","JUPITER","SATURN","URANUS","NEPTUNE","PLUTO","ECLIPSE","SOLAR"
  ],

  Time: [
    "SECOND","MINUTE","HOUR","DAY","WEEK","MONTH","YEAR","DECADE","CENTURY","MILLENNIUM",
    "MORNING","NOON","AFTERNOON","EVENING","NIGHT","MIDNIGHT","DAWN","DUSK","TODAY","TOMORROW",
    "YESTERDAY","PAST","PRESENT","FUTURE","DEADLINE","SCHEDULE","CALENDAR","CLOCK","ALARM","TIMEZONE"
  ],

  Shapes: [
    "CIRCLE","SQUARE","TRIANGLE","RECTANGLE","OVAL","DIAMOND","STAR","HEART","CUBE","SPHERE",
    "CYLINDER","CONE","PYRAMID","HEXAGON","PENTAGON","OCTAGON","DECAGON","ELLIPSE","ARC","ANGLE",
    "LINE","CURVE","EDGE","FACE","VERTEX","PLANE","SOLID","FORM","PATTERN","SYMMETRY"
  ],

  Materials: [
    "WOOD","METAL","PLASTIC","GLASS","STONE","BRICK","CONCRETE","STEEL","IRON","COPPER",
    "ALUMINUM","SILVER","GOLD","FABRIC","COTTON","WOOL","SILK","LEATHER","RUBBER","CERAMIC",
    "PORCELAIN","CLAY","PAPER","CARDBOARD","FOAM","CARBON","FIBER","RESIN","LATEX","NYLON"
  ],

  Communication: [
    "MESSAGE","EMAIL","LETTER","CHAT","CALL","VIDEO","AUDIO","SIGNAL","BROADCAST","STREAM",
    "POST","COMMENT","REPLY","FORWARD","ATTACHMENT","SUBJECT","CONTENT","CHANNEL","NETWORK","CONTACT",
    "PROFILE","USERNAME","PASSWORD","LOGIN","LOGOUT","SESSION","NOTIFICATION","ALERT","STATUS","UPDATE"
  ],

  Education: [
    "SCHOOL","COLLEGE","UNIVERSITY","CLASS","LESSON","LECTURE","COURSE","SUBJECT","TOPIC","MODULE",
    "STUDENT","TEACHER","PROFESSOR","TUTOR","HOMEWORK","ASSIGNMENT","PROJECT","EXAM","TEST","QUIZ",
    "GRADE","SCORE","RESULT","DIPLOMA","DEGREE","CERTIFICATE","KNOWLEDGE","LEARNING","STUDY","REVISION"
  ],

  Finance: [
    "MONEY","CASH","COIN","BANK","ACCOUNT","SAVINGS","CREDIT","DEBIT","LOAN","INTEREST",
    "INVESTMENT","STOCK","BOND","ETF","FUND","MARKET","TRADE","PROFIT","LOSS","REVENUE",
    "SALARY","WAGE","INCOME","EXPENSE","BUDGET","TAX","INVOICE","PAYMENT","TRANSFER","BALANCE"
  ],

  Health: [
    "DOCTOR","PATIENT","CLINIC","HOSPITAL","MEDICINE","TABLET","VACCINE","THERAPY","TREATMENT","RECOVERY",
    "SYMPTOM","DIAGNOSIS","CONDITION","DISEASE","INFECTION","VIRUS","BACTERIA","IMMUNITY","FITNESS","EXERCISE",
    "DIET","NUTRITION","PROTEIN","VITAMIN","MINERAL","HYDRATION","SLEEP","REST","STRESS","WELLNESS"  
  ]
Transportation: [
  "CAR","TRUCK","BUS","TRAIN","TRAM","SUBWAY","SCOOTER","MOTORBIKE","BICYCLE","SKATEBOARD",
  "AIRPLANE","HELICOPTER","GLIDER","JET","BOAT","SHIP","FERRY","SUBMARINE","YACHT","CANOE",
  "KAYAK","RAFT","TANK","TRACTOR","CRANE","FORKLIFT","VAN","SUV","SEDAN","COUPE"
],

Clothing: [
  "SHIRT","PANTS","JEANS","SHORTS","SKIRT","DRESS","JACKET","COAT","HOODIE","SWEATER",
  "SOCKS","SHOES","BOOTS","SANDALS","SNEAKERS","HAT","CAP","BEANIE","SCARF","GLOVES",
  "BELT","TIE","SUIT","BLAZER","VEST","PYJAMAS","UNDERWEAR","BRIEFS","BOXERS","BATHROBE"
],

BodyParts: [
  "HEAD","BRAIN","EYES","EARS","NOSE","MOUTH","TEETH","TONGUE","NECK","SHOULDERS",
  "ARMS","ELBOW","WRIST","HANDS","FINGERS","CHEST","BACK","SPINE","WAIST","HIPS",
  "LEGS","KNEE","ANKLE","FEET","TOES","HEART","LUNGS","LIVER","STOMACH","MUSCLES"
],

Weather: [
  "SUNNY","CLOUDY","RAINY","STORMY","WINDY","FOGGY","SNOWY","ICY","HUMID","DRY",
  "HOT","COLD","WARM","COOL","FREEZING","BOILING","BREEZY","OVERCAST","DROUGHT","FLOOD",
  "THUNDER","LIGHTNING","HAIL","BLIZZARD","CYCLONE","HURRICANE","TORNADO","MONSOON","RAINBOW","MIST"
],

Space: [
  "PLANET","STAR","GALAXY","NEBULA","COMET","ASTEROID","METEOR","ORBIT","GRAVITY","VACUUM",
  "SATELLITE","ROCKET","SPACESHIP","ASTRONAUT","COSMONAUT","TELESCOPE","OBSERVATORY","CONSTELLATION","UNIVERSE","COSMOS",
  "MARS","VENUS","EARTH","JUPITER","SATURN","URANUS","NEPTUNE","PLUTO","ECLIPSE","SOLAR"
],

Time: [
  "SECOND","MINUTE","HOUR","DAY","WEEK","MONTH","YEAR","DECADE","CENTURY","MILLENNIUM",
  "MORNING","NOON","AFTERNOON","EVENING","NIGHT","MIDNIGHT","DAWN","DUSK","TODAY","TOMORROW",
  "YESTERDAY","PAST","PRESENT","FUTURE","DEADLINE","SCHEDULE","CALENDAR","CLOCK","ALARM","TIMEZONE"
],

Shapes: [
  "CIRCLE","SQUARE","TRIANGLE","RECTANGLE","OVAL","DIAMOND","STAR","HEART","CUBE","SPHERE",
  "CYLINDER","CONE","PYRAMID","HEXAGON","PENTAGON","OCTAGON","DECAGON","ELLIPSE","ARC","ANGLE",
  "LINE","CURVE","EDGE","FACE","VERTEX","PLANE","SOLID","FORM","PATTERN","SYMMETRY"
],

Materials: [
  "WOOD","METAL","PLASTIC","GLASS","STONE","BRICK","CONCRETE","STEEL","IRON","COPPER",
  "ALUMINUM","SILVER","GOLD","FABRIC","COTTON","WOOL","SILK","LEATHER","RUBBER","CERAMIC",
  "PORCELAIN","CLAY","PAPER","CARDBOARD","FOAM","CARBON","FIBER","RESIN","LATEX","NYLON"
],

Communication: [
  "MESSAGE","EMAIL","LETTER","CHAT","CALL","VIDEO","AUDIO","SIGNAL","BROADCAST","STREAM",
  "POST","COMMENT","REPLY","FORWARD","ATTACHMENT","SUBJECT","CONTENT","CHANNEL","NETWORK","CONTACT",
  "PROFILE","USERNAME","PASSWORD","LOGIN","LOGOUT","SESSION","NOTIFICATION","ALERT","STATUS","UPDATE"
],

Education: [
  "SCHOOL","COLLEGE","UNIVERSITY","CLASS","LESSON","LECTURE","COURSE","SUBJECT","TOPIC","MODULE",
  "STUDENT","TEACHER","PROFESSOR","TUTOR","HOMEWORK","ASSIGNMENT","PROJECT","EXAM","TEST","QUIZ",
  "GRADE","SCORE","RESULT","DIPLOMA","DEGREE","CERTIFICATE","KNOWLEDGE","LEARNING","STUDY","REVISION"
],

Finance: [
  "MONEY","CASH","COIN","BANK","ACCOUNT","SAVINGS","CREDIT","DEBIT","LOAN","INTEREST",
  "INVESTMENT","STOCK","BOND","ETF","FUND","MARKET","TRADE","PROFIT","LOSS","REVENUE",
  "SALARY","WAGE","INCOME","EXPENSE","BUDGET","TAX","INVOICE","PAYMENT","TRANSFER","BALANCE"
],

Health: [
  "DOCTOR","PATIENT","CLINIC","HOSPITAL","MEDICINE","TABLET","VACCINE","THERAPY","TREATMENT","RECOVERY",
  "SYMPTOM","DIAGNOSIS","CONDITION","DISEASE","INFECTION","VIRUS","BACTERIA","IMMUNITY","FITNESS","EXERCISE",
  "DIET","NUTRITION","PROTEIN","VITAMIN","MINERAL","HYDRATION","SLEEP","REST","STRESS","WELLNESS"
],

Furniture: [
  "SOFA","CHAIR","TABLE","DESK","CABINET","SHELF","BED","MATTRESS","LAMP","BOOKCASE",
  "STOOL","COUCH","COFFEE","SIDE","NIGHTSTAND","DRAWER","DRESSER","BENCH","WARDROBE","ARMCHAIR",
  "OTTOMAN","CUPBOARD","TVSTAND","RUG","CARPET","MIRROR","PICTURE","FRAME","SHELVES","HANGER"
],

Tools: [
  "HAMMER","SCREWDRIVER","WRENCH","PLIERS","SAW","DRILL","NAILS","SCREWS","BOLT","NUT",
  "LEVEL","CHISEL","SANDER","TAPE","MEASURE","KNIFE","CUTTER","AXE","MOP","BROOM",
  "SHOVEL","HOE","RAKE","LADDER","PAINT","BRUSH","ROLLER","GLUE","CLAMP","VISE"
],

Instruments: [
  "GUITAR","PIANO","DRUMS","FLUTE","VIOLIN","TRUMPET","SAXOPHONE","TROMBONE","HARP","CELLO",
  "BASS","CLARINET","OBOE","BAGPIPE","ACCORDION","MANDOLIN","BANJO","UKULELE","TUBA","SITAR",
  "XYLAPHONE","MARIMBA","TAMBOURINE","CONGA","DJEMBE","SYNTH","KEYBOARD","ORGAN","GLOCKENSPIEL","PANFLUTE"
],

VehiclesWater: [
  "BOAT","SHIP","YACHT","FERRY","SUBMARINE","KAYAK","CANOE","RAFT","SPEEDBOAT","SCHOONER",
  "CATAMARAN","CRUISE","VESSEL","STEAMER","SAILBOAT","JUNK","BARGE","TUG","FISHING","FERRYBOAT",
  "DINGHY","ROWBOAT","PADDLE","KETCH","TRAWLER","YACHTING","MOTORBOAT","FRIGATE","CORVETTE","CLIPPER"
],

VehiclesAir: [
  "AIRPLANE","JET","GLIDER","HELICOPTER","BALLOON","PARACHUTE","DRONE","BIPLANE","TRICOPTER","QUADCOPTER",
  "SPACESHIP","ROCKET","MOTHERSHIP","SPACECRAFT","CARRIER","FIGHTER","BOMBER","GUNSHIP","SEAPLANE","FLOATPLANE",
  "ULTRALIGHT","GYROCOPTER","DIRIGIBLE","ZEPLIN","BALLONET","HANGGLIDER","PARAGLIDER","WINGLET","AEROBATIC","STOL"
],

Politics: [
  "PRESIDENT","PRIME","MINISTER","SENATOR","GOVERNOR","MAYOR","COUNCIL","CABINET","PARLIAMENT","CONGRESS",
  "VOTE","ELECTION","DEBATE","LAW","BILL","ACT","CONSTITUTION","PARTY","LEADER","OPPOSITION",
  "DIPLOMAT","AMBASSADOR","EMBASSY","TREATY","NEGOTIATION","POLICY","REFORM","CAMPAIGN","COALITION","LEGISLATION"
],

Science: [
  "PHYSICS","CHEMISTRY","BIOLOGY","ASTRONOMY","GEOLOGY","ECOLOGY","GENETICS","MICROBIOLOGY","NEUROSCIENCE","BOTANY",
  "ZOOLOGY","MATHEMATICS","STATISTICS","ASTROPHYSICS","METEOROLOGY","ANATOMY","PHARMACOLOGY","BIOCHEMISTRY","ENGINEERING","TECHNOLOGY",
  "ROBOTICS","QUANTUM","RELATIVITY","OPTICS","THERMODYNAMICS","ELECTRICITY","MAGNETISM","ENERGY","GRAVITY","FORCE"
],

History: [
  "WAR","REVOLUTION","EMPIRE","KINGDOM","DYNASTY","MONARCH","PRESIDENT","COLONY","SETTLEMENT","DISCOVERY",
  "CONQUEST","BATTLE","TREATY","ALLIANCE","REIGN","ERA","PERIOD","CENTURY","MILLENNIUM","AGE",
  "CIVILIZATION","CULTURE","TRADITION","HERITAGE","MONUMENT","ARCHAEOLOGY","ARTIFACT","HISTORY","LEGEND","MYTH"
],

Literature: [
  "NOVEL","POEM","POETRY","STORY","FICTION","NONFICTION","ESSAY","DRAMA","TRAGEDY","COMEDY",
  "PLAY","NARRATIVE","CHAPTER","VERSE","LINE","PROSE","SHORTSTORY","BIOGRAPHY","AUTOBIOGRAPHY","FABLE",
  "MYTH","LEGEND","EPIC","SONNET","HAIKU","PARABLE","SCRIPT","SCREENPLAY","ROMANCE","MYSTERY"
],

Languages: [
  "ENGLISH","FRENCH","SPANISH","GERMAN","ITALIAN","PORTUGUESE","RUSSIAN","CHINESE","JAPANESE","KOREAN",
  "ARABIC","HINDI","BENGALI","URDU","PERSIAN","TURKISH","SWEDISH","DUTCH","NORWEGIAN","FINNISH",
  "POLISH","CZECH","SLOVAK","GREEK","HEBREW","THAI","VIETNAMESE","LAO","TAGALOG","MALAY"
],

Art: [
  "PAINTING","SCULPTURE","DRAWING","PHOTOGRAPHY","MOSAIC","FRESCO","CERAMICS","CALLIGRAPHY","GRAFFITI","ETCHING",
  "COLLAGE","ILLUSTRATION","ENGRAVING","CARVING","PRINTMAKING","TEXTILE","WEAVING","KNITTING","CERAMIC","WATERCOLOR",
  "OIL","ACRYLIC","INK","PASTEL","CHARCOAL","GRAPHITE","STENCIL","DIGITAL","MURAL","SKETCH"
],

NaturePlants: [
  "TREE","FLOWER","GRASS","BUSH","FERN","MOSS","CACTUS","VINE","SHRUB","LEAF",
  "ROOT","SEED","FRUIT","VEGETABLE","HERB","SPICE","POD","BULB","BRANCH","STEM",
  "FLOWERBED","GARDEN","FOREST","JUNGLE","RAINFOREST","MEADOW","PLAINS","SAVANNA","PARK","RESERVE"
],

Gems: [
  "DIAMOND","RUBY","SAPPHIRE","EMERALD","OPAL","PEARL","TOPAZ","AMETHYST","AQUAMARINE","CITRINE",
  "GARNET","TURQUOISE","ONYX","JADE","PERIDOT","QUARTZ","TANZANITE","MOONSTONE","SPINEL","CHALCEDONY",
  "BERYL","CHRYSOLITE","CORUNDUM","LABRADORITE","AGATE","LAPIS","MALACHITE","OBSIDIAN","RUBELLITE","SUGILITE"
],

FurnitureRoom: [
  "LIVINGROOM","BEDROOM","KITCHEN","BATHROOM","DININGROOM","OFFICE","STUDY","HALLWAY","GARAGE","BALCONY",
  "LOUNGE","ATTIC","BASEMENT","SUNROOM","LIBRARY","PLAYROOM","STORAGE","PANTRY","CLOSET","MUDROOM",
  "PORCH","DECK","GARDEN","PATIO","VERANDA","LOBBY","STUDIO","CONSERVATORY","GYM","THEATER"
]
Electronics: [
  "TV","RADIO","HEADPHONES","SPEAKER","MICROPHONE","CAMERA","SMARTPHONE","LAPTOP","TABLET","MONITOR",
  "PRINTER","ROUTER","MODEM","KEYBOARD","MOUSE","PROJECTOR","DRONE","GAMEPAD","CONSOLE","CHARGER",
  "USB","HDMI","BATTERY","ADAPTER","SENSOR","LIGHT","SCREEN","WEARABLE","CAMCORDER","EBOOK"
],

Games: [
  "CHESS","CHECKERS","SCRABBLE","MONOPOLY","POKER","UNO","DOMINO","MAHJONG","BACKGAMMON","GO",
  "BRIDGE","RISK","CLUE","CARDS","DICE","BINGO","JENGA","PUZZLE","SOLO","SOLITAIRE",
  "TIC","TAC","TOE","MINESWEEPER","SOLITAIRE","WORDSEARCH","CROSSWORD","SUDOKU","TRIVIA","QUIZ"
],

VehiclesLand: [
  "CAR","TRUCK","BUS","MOTORCYCLE","BICYCLE","SCOOTER","TRACTOR","VAN","SUV","MOTORBIKE",
  "CART","TRAIN","TRAM","TROLLEY","CAB","MINIBUS","TAXI","RICKSHAW","SEGWAY","ROLLER",
  "SKATEBOARD","MOUNTAINBIKE","ROADBIKE","E_BIKE","UNIMOG","BUGGY","ATV","SNOWMOBILE","CYCLE","VELO"
],

Flowers: [
  "ROSE","TULIP","DAISY","LILY","SUNFLOWER","DAFFODIL","ORCHID","PEONY","IRIS","MARIGOLD",
  "JASMINE","VIOLET","HYACINTH","CARNATION","GARDENIA","AZALEA","CAMELLIA","CHRYSANTHEMUM","POPPY","LAVENDER",
  "HELIOTROPE","FUCHSIA","HIBISCUS","PANSY","ASTER","DAHLIA","GLOXINIA","IMPATIENS","MIMOSA","WISTERIA"
],

Insects: [
  "ANT","BEE","BUTTERFLY","MOTH","BEETLE","COCKROACH","CRICKET","GRASSHOPPER","LADYBUG","DRAGONFLY",
  "MAYFLY","TERMITES","WASP","HORNET","CICADA","FLEA","MOSQUITO","GNAT","FLY","LICE",
  "SPIDER","SCORPION","TICK","MITE","APHID","CATERPILLAR","LARVA","NYMPH","SILKWORM","CRAB"
],

Birds: [
  "SPARROW","ROBIN","CROW","RAVEN","EAGLE","FALCON","HAWK","OWL","PARROT","PARAKEET",
  "CANARY","FINCH","PEACOCK","PIGEON","DOVE","WOODPECKER","KINGFISHER","SWAN","DUCK","GOOSE",
  "HERON","IBIS","STORK","FLAMINGO","CRANE","ALBATROSS","SEAGULL","CONDOR","TURKEY","QUAIL"
],

Reptiles: [
  "SNAKE","LIZARD","TURTLE","TORTOISE","IGUANA","GECKO","CHAMELEON","CROCODILE","ALLIGATOR","GAVIAL",
  "SNAKEHEAD","MONITOR","SKINK","VIPER","PYTHON","BOA","COBRA","KRAIT","GILA","DRAGON",
  "ANOLE","CHINCHILLA","TERRAPIN","BASILISK","TUI","MONITO","GECKOLET","SERPENT","RATTLESNAKE","IGUANALET"
],

SeaAnimals: [
  "SHARK","DOLPHIN","WHALE","OCTOPUS","SQUID","SEAL","OTTER","CRAB","LOBSTER","JELLYFISH",
  "STARFISH","CORAL","ANEMONE","TURTLE","SEAHORSE","CLAM","MUSSEL","OYSTER","SHELL","RAY",
  "MANTA","EEL","FISH","COD","SALMON","TUNA","GROUPER","ANGELFISH","BETTA","GOLDFISH"
],

Trees: [
  "OAK","MAPLE","PINE","CEDAR","SPRUCE","BIRCH","WILLOW","CHERRY","APPLE","PEAR",
  "MANGO","PALM","BAOBAB","EUCALYPTUS","ASH","ELM","FIR","SEQUOIA","REDWOOD","TEAK",
  "MAHOGANY","WALNUT","ALDER","HAWTHORN","LOCUST","CHESTNUT","HEMLock","SYCAMORE","BEECH","HOLLY"
],

Planets: [
  "MERCURY","VENUS","EARTH","MARS","JUPITER","SATURN","URANUS","NEPTUNE","PLUTO","CERES",
  "ERIS","HAUMEA","MAKEMAKE","IO","EUROPA","GANYMEDE","CALLISTO","TITAN","ENCLADEUS","TRITON",
  "MIRANDA","TITANIA","OBERON","UMBRIEL","CHARON","PHOBOS","DEIMOS","PHOEBE","DIONE","RHEA"
],

Mythology: [
  "ZEUS","HERA","POSEIDON","DEMETER","APOLLO","ARTEMIS","ARES","ATHENA","HEPHAESTUS","APHRODITE",
  "HERMES","HESTIA","DIONYSUS","HADES","PERSEPHONE","ODIN","THOR","LOKI","FREYA","FREYR",
  "BALDER","TYR","FRIGG","HEIMDALL","NJORD","SKADI","RA","ISIS","OSIRIS","HORUS"
],

PlanetsMoons: [
  "MOON","PHOBOS","DEIMOS","IO","EUROPA","GANYMEDE","CALLISTO","TITAN","ENCLADEUS","TRITON",
  "MIRANDA","TITANIA","OBERON","UMBRIEL","CHARON","TETHYS","DIONE","RHEA","JANUS","EPIMETHEUS",
  "MIMAS","ENCELADUS","TITANIA","OBERON","UMBriel","PHOBOS","DEIMOS","GANYMEDE","CALLISTO","IO"
],

Oceans: [
  "PACIFIC","ATLANTIC","INDIAN","ARCTIC","SOUTHERN","CARIBBEAN","MEDITERRANEAN","BALTIC","NORTHSEA","CORAL",
  "RED","BLACK","BAHRAIN","PHILIPPINE","CHINA","JAPANESE","SARGASSO","ANDAMAN","BERING","BERMUDA",
  "GULF","HUDSON","ARAL","CASPIAN","IONIAN","ADRIATIC","AEGEAN","LIGURIAN","TYRRHENIAN","CANTABRIAN"
],

ProgrammingLanguages: [
  "JAVASCRIPT","PYTHON","JAVA","C","CPLUSPLUS","RUBY","GO","SWIFT","KOTLIN","PHP",
  "RUST","SCALA","PERL","OBJECTIVE_C","TYPESCRIPT","HTML","CSS","SQL","MATLAB","SHELL",
  "DART","LUA","FORTRAN","COBOL","VISUALBASIC","ASSEMBLY","PROLOG","HASKELL","ELIXIR","ERLANG"
],

PlanetsGas: [
  "JUPITER","SATURN","URANUS","NEPTUNE","MERCURY","VENUS","EARTH","MARS","PLUTO","CERES",
  "ERIS","HAUMEA","MAKEMAKE","IO","EUROPA","GANYMEDE","CALLISTO","TITAN","ENCLADEUS","TRITON",
  "MIRANDA","TITANIA","OBERON","UMBriel","CHARON","PHOBOS","DEIMOS","PHOEBE","DIONE","RHEA"
],

Desserts: [
  "CAKE","PIE","ICECREAM","COOKIE","BROWNIE","MUFFIN","DONUT","CUPCAKE","TART","PUDDING",
  "CUSTARD","SORBET","GELATO","PANCAKE","WAFFLE","CREPE","TRUFFLE","MACARON","BISCUIT","CHOCOLATE",
  "CANDY","MARSHMALLOW","TOFFEE","CARAMEL","PRALINE","FUDGE","BREADPUDDING","CHURROS","TARTLET","ECLAIR"
],

DessertsChocolate: [
  "CHOCOLATE","DARK","MILK","WHITE","COCOA","GANACHE","TRUFFLE","PRALINE","MOUSSE","FUDGE",
  "BROWNIE","BAR","BONBON","CANDY","CHIP","COOKIES","PASTRY","CAKE","TART","ECLAIR",
  "FONDUE","CHOCOLATECAKE","CHOCOLATEPIE","COCOAFLAKE","CHOCOLATEMOUSSE","COCOACHUNK","COCOABARS","COCOAPASTE","COCOAPUFF","CHOCOLATEBALL"
],

ToolsConstruction: [
  "HAMMER","SCREWDRIVER","WRENCH","PLIERS","SAW","DRILL","NAILS","SCREWS","BOLT","NUT",
  "LEVEL","CHISEL","SANDER","TAPE","MEASURE","KNIFE","CUTTER","AXE","MOP","BROOM",
  "SHOVEL","HOE","RAKE","LADDER","PAINT","BRUSH","ROLLER","GLUE","CLAMP","VISE"
],

VehiclesSpecial: [
  "AMBULANCE","FIRETRUCK","POLICECAR","TAXI","MILITARY","TRACTOR","TRAILER","TOWTRUCK","ICECREAMTRUCK","FOODTRUCK",
  "MINIVAN","BUS","COACH","TRACTOR","TANK","TUGBOAT","CARGO","FERRY","YACHT","SUBMARINE",
  "JET","HELICOPTER","HOT_AIR_BALLOON","PARAGLIDER","ULTRALIGHT","BICYCLE","SCOOTER","SNOWMOBILE","MOTORBIKE","SKATEBOARD"
],

Kitchen: [
  "PAN","POT","KNIFE","SPOON","FORK","PLATE","BOWL","MUG","GLASS","CUTTINGBOARD",
  "GRATER","PEELER","WHISK","BLENDER","FOODPROCESSOR","STOVE","OVEN","MICROWAVE","TOASTER","KETTLE",
  "COLANDER","SIEVE","TRAY","TIMER","TONGS","SPATULA","LADLE","MEASURECUP","SCALES","JAR"
]
Numbers: [
  "ONE","TWO","THREE","FOUR","FIVE","SIX","SEVEN","EIGHT","NINE","TEN",
  "ELEVEN","TWELVE","THIRTEEN","FOURTEEN","FIFTEEN","SIXTEEN","SEVENTEEN","EIGHTEEN","NINETEEN","TWENTY",
  "THIRTY","FORTY","FIFTY","SIXTY","SEVENTY","EIGHTY","NINETY","HUNDRED","THOUSAND","MILLION"
],

PlanetsRings: [
  "SATURN","JUPITER","URANUS","NEPTUNE","RINGS","MERCURY","VENUS","EARTH","MARS","PLUTO",
  "CERES","ERIS","HAUMEA","MAKEMAKE","IO","EUROPA","GANYMEDE","CALLISTO","TITAN","ENCLADEUS",
  "TRITON","MIRANDA","TITANIA","OBERON","UMBriel","CHARON","PHOBOS","DEIMOS","PHOEBE","DIONE"
],

ComputerParts: [
  "CPU","GPU","RAM","HDD","SSD","MOTHERBOARD","PSU","FAN","COOLER","CASE",
  "MONITOR","KEYBOARD","MOUSE","PRINTER","SPEAKER","HEADPHONES","MICROPHONE","USB","HDMI","CABLE",
  "NETWORKCARD","BLUETOOTH","WIRELESS","PORT","BIOS","FIRMWARE","SOFTWARE","DRIVER","TOUCHPAD","TRACKBALL"
],

FurnitureOffice: [
  "DESK","CHAIR","CABINET","SHELF","BOOKCASE","SOFA","TABLE","STOOL","COUCH","FILING",
  "DRAWER","CUPBOARD","BENCH","ARMCHAIR","PEDESTAL","BOARD","WHITEBOARD","NOTICEBOARD","LAMP","RUG",
  "CARPET","MIRROR","PICTURE","FRAME","CHAIRMAT","LOUNGE","STORAGE","LOBBY","RECEPTION","CONFERENCE"
],

Jewelry: [
  "RING","NECKLACE","BRACELET","EARRINGS","PENDANT","CHAIN","WATCH","BROOCH","CUFFLINKS","ANKLET",
  "TIARA","CROWN","BEADS","CHARM","LOCKET","BANGLE","AMULET","TALISMAN","BROOCH","PIN",
  "JEWEL","GEM","DIAMOND","SAPPHIRE","RUBY","EMERALD","PEARL","OPAL","TOPAZ","AMETHYST"
],

VehiclesExtreme: [
  "SNOWMOBILE","ATV","BUGGY","DRIFT","RACECAR","MOTORBIKE","JETSKI","KART","SCOOTER","UNIMOG",
  "MONOCYCLE","E_BIKE","SEGWAY","ROLLER","SKATEBOARD","SURFBOARD","WINDSURF","KITESURF","PARAGLIDER","ULTRALIGHT",
  "GLIDER","JET","BALLOON","PARACHUTE","DRONE","AIRCRAFT","HELICOPTER","SPACECRAFT","ROCKET","SPACESHIP"
],

Fantasy: [
  "DRAGON","UNICORN","FAIRY","TROLL","ELF","DWARF","GOBLIN","ORC","WITCH","SORCERER",
  "MAGIC","SPELL","POTION","SWORD","SHIELD","ARMOR","CASTLE","KINGDOM","PRINCESS","PRINCE",
  "KNIGHT","GIANT","BEAST","DEMON","ANGEL","SPIRIT","GHOST","VAMPIRE","ZOMBIE","WYVERN"
],

Superheroes: [
  "BATMAN","SUPERMAN","SPIDERMAN","WONDERWOMAN","FLASH","AQUAMAN","IRONMAN","THOR","HULK","BLACKWIDOW",
  "CAPTAINAMERICA","HAWKEYE","DOCTORSTRANGE","BLACKPANTHER","ANTMAN","WASP","VISION","SCARLETWITCH","LOKI","THANOS",
  "DEADPOOL","SILVERSURFER","GREENLANTERN","CYBORG","SUPERSPEED","FLIGHT","STRENGTH","INTELLIGENCE","MAGIC","TECH"
],

MusicGenres: [
  "ROCK","POP","JAZZ","BLUES","SOUL","FUNK","DISCO","TECHNO","HOUSE","TRANCE",
  "HIPHOP","RAP","REGGAE","SKA","METAL","PUNK","GRUNGE","INDIE","FOLK","COUNTRY",
  "CLASSICAL","OPERA","CHORAL","SYMPHONY","ORCHESTRA","PIANO","GUITAR","DRUMS","BASS","VIOLIN"
],

ComputingConcepts: [
  "ALGORITHM","VARIABLE","FUNCTION","ARRAY","OBJECT","CLASS","METHOD","LOOP","CONDITION","RECURSION",
  "STACK","QUEUE","TREE","GRAPH","DATABASE","SERVER","CLIENT","PROTOCOL","API","FRAMEWORK",
  "SOFTWARE","HARDWARE","NETWORK","SECURITY","ENCRYPTION","PASSWORD","LOGIN","SESSION","CACHE","THREAD"
],

GamesVideo: [
  "FORTNITE","MINECRAFT","CALL","DUTY","LEAGUE","LEGENDS","OVERWATCH","CSGO","VALORANT","ROCKETLEAGUE",
  "AMONGUS","PUBG","APEX","GEARS","HALO","SKYRIM","WITCHER","ZELDA","MARIO","SONIC",
  "POKEMON","ANIMALCROSSING","SIMS","FIFA","NBA","MADDEN","TES","WOW","DIABLO","STARCRAFT"
],

Occupations: [
  "DOCTOR","NURSE","TEACHER","LAWYER","ENGINEER","ARCHITECT","DESIGNER","WRITER","EDITOR","REPORTER",
  "CHEF","BAKER","COOK","FARMER","GARDENER","DRIVER","PILOT","CAPTAIN","SAILOR","FISHER",
  "ACTOR","SINGER","DANCER","PAINTER","SCULPTOR","PHOTOGRAPHER","DIRECTOR","PRODUCER","CAMERAMAN","EDITORIAL"
],

VehiclesHistoric: [
  "STAGECOACH","CARAVEL","GALLEY","DINGHY","COACH","CARRIAGE","CHAISE","CHUCKWAGON","SEDANCHAIR","BARK",
  "TRIREME","FRIGATE","SCHOONER","GALLEON","BRIGANTINE","CLIPPER","STEAMBOAT","LOCOMOTIVE","BICYCLE","TRICYCLE",
  "ROLLER","SLED","SLEDGE","CARRIOL","TROLLEY","CAB","RICKSHAW","STAGE","DORY","RAFT"
],

MythicalCreatures: [
  "DRAGON","UNICORN","FAIRY","TROLL","ELF","DWARF","GOBLIN","ORC","WITCH","SORCERER",
  "MAGIC","SPELL","POTION","SWORD","SHIELD","ARMOR","CASTLE","KINGDOM","PRINCESS","PRINCE",
  "KNIGHT","GIANT","BEAST","DEMON","ANGEL","SPIRIT","GHOST","VAMPIRE","ZOMBIE","WYVERN"
],

TransportAncient: [
  "CART","CHARIOT","BOAT","RAFT","CANOE","SLED","HORSE","CAMEL","ELEPHANT","OX",
  "DONKEY","MULE","COACH","GALLEY","TRIREME","BARGE","JUNK","KAYAK","SLEDGE","STAGECOACH",
  "CARAVEL","CLIPPER","BRIGANTINE","FRIGATE","CARRIAGE","CHAIR","ROWBOAT","DINGHY","BARK","VIKINGSHIP"
],

BodyActions: [
  "RUN","WALK","JUMP","SWIM","CLIMB","CRAWL","DANCE","SIT","STAND","LIE",
  "THROW","CATCH","KICK","PUNCH","GRAB","REACH","BEND","STRETCH","TURN","SPIN",
  "ROLL","SLIDE","CREEP","TIPTOE","SPRINT","SQUAT","PUSH","PULL","LIFT","CARRY"
],

FurnitureKitchen: [
  "TABLE","CHAIR","STOOL","CABINET","SHELF","PANTRY","COUNTER","ISLAND","DRAWER","RACK",
  "POT","PAN","KNIFE","SPOON","FORK","PLATE","BOWL","GLASS","MUG","BLENDER",
  "OVEN","STOVE","MICROWAVE","TOASTER","KETTLE","COLANDER","TIMER","WHISK","TRAY","SPATULA"
],

BirdsExotic: [
  "PARROT","MACAW","COCKATIEL","LOVEBIRD","CANARY","FINCH","BUDGERIGAR","COCKATOO","LOON","KINGFISHER",
  "TOUCAN","FLAMINGO","PEACOCK","QUAIL","DOVE","PIGEON","HERON","IBIS","STORK","SWAN",
  "DUCK","GOOSE","ALBATROSS","SEAGULL","CONDOR","OSPREY","FALCON","HAWK","EAGLE","OWL"
],

Vegetables: [
  "CARROT","POTATO","ONION","TOMATO","LETTUCE","SPINACH","CABBAGE","PEAS","BEANS","BROCCOLI",
  "CAULIFLOWER","CUCUMBER","ZUCCHINI","EGGPLANT","PEPPER","RADISH","TURNIP","SWEETCORN","GARLIC","GINGER",
  "CELERY","PARSNIP","LEEK","SCALLION","MUSHROOM","KALE","ARTICHOKE","ASPARAGUS","OKRA","FENNEL"
],

Spices: [
  "SALT","PEPPER","CINNAMON","NUTMEG","CLOVES","CARDAMOM","GINGER","TURMERIC","SAFFRON","PAPRIKA",
  "CHILI","BASIL","OREGANO","THYME","ROSEMARY","MINT","PARSLEY","CORIANDER","DILL","TARRAGON",
  "FENNEL","ANISE","CUMIN","CLOVE","GARLIC","ONION","CHIVE","SAGE","MARJORAM","CHERVIL"
],

FurnitureBedroom: [
  "BED","MATTRESS","PILLOW","SHEET","BLANKET","COMFORTER","DUVET","NIGHTSTAND","WARDROBE","DRESSER",
  "LAMP","CHAIR","BENCH","STOOL","MIRROR","RUG","CARPET","CLOSET","CUSHION","HEADBOARD",
  "FOOTBOARD","FRAME","BUREAU","ARMOIRE","TRUNK","CHEST","SHELF","STORAGE","DESK","BOOKCASE"
],

FictionalPlaces: [
  "MORDOR","NARNIA","HOGWARTS","MIDDLEEARTH","WONDERLAND","ATLANTIS","ELDORADO","OMEGAVILLE","PANEM","GOTHAM",
  "METROPOLIS","SPRINGFIELD","BEDROCK","ELBONIA","GENERICA","ZION","KRYPTON","VULCAN","ARKHAM","OMEGA",
  "VALINOR","BRAZORIA","SHANGRI_LA","EQUILIBRIA","CAMELOT","OLYMPIA","TERRA","AVALON","RIVENDELL","MYST"
],

VehiclesFuturistic: [
  "HOVERBOARD","JETPACK","FUTURECAR","FLYINGCAR","TUNNELTRAIN","MONORAIL","MAGLEV","SPACESHUTTLE","DRONE","ROBOTICBIKE",
  "SKATEBOT","AUTONOMOUSCAR","HYPERLOOP","AIRSHIP","SOLARCAR","LUNARROVER","MARSROVER","SPACEMODULE","CYBERBIKE","TRONBIKE",
  "E_BIKE","E_SCOOTER","SEGWAY","JETBIKE","FLOATINGCAR","SKYTRAIN","CIVICAR","NEOCRAFT","DRONESHIP","TUNNELCAR"
