const THEMES = {
  Animals: [
    "DOG","CAT","HORSE","TIGER","LION","WOLF","FOX","BEAR","SHEEP","GOAT",
    "COW","PIG","MOUSE","RABBIT","DEER","MONKEY","APE","KOALA","PANDA","ZEBRA",
    "CAMEL","OTTER","SEAL","WHALE","DOLPHIN","SHARK","EAGLE","OWL","CROW","FALCON"
  ],

  Countries: [
    "FRANCE","SPAIN","ITALY","GERMANY","BELGIUM","SWEDEN","NORWAY","POLAND","GREECE","PORTUGAL",
    "CANADA","BRAZIL","ARGENTINA","CHILE","PERU","MEXICO","COLOMBIA","PANAMA","CUBA","JAMAICA",
    "JAPAN","CHINA","KOREA","INDIA","THAILAND","VIETNAM","NEPAL","BHUTAN","LAOS","MALAYSIA"
  ],

  Brands: [
    "APPLE","GOOGLE","MICROSOFT","AMAZON","META","TESLA","NIKE","ADIDAS","PUMA","REEBOK",
    "SONY","SAMSUNG","INTEL","NVIDIA","IBM","ORACLE","SPOTIFY","NETFLIX","DISNEY","UBER",
    "AIRBNB","PAYPAL","STRIPE","VISA","MASTERCARD","COCA","PEPSI","NESTLE","SHELL","TOTAL"
  ],

  Food: [
    "BREAD","CHEESE","BUTTER","YOGURT","PASTA","PIZZA","BURGER","STEAK","CHICKEN","BACON",
    "SALMON","TUNA","SHRIMP","RICE","NOODLE","SOUP","SALAD","TOMATO","ONION","GARLIC",
    "PEPPER","CARROT","POTATO","APPLE","BANANA","ORANGE","MANGO","GRAPE","LEMON","PEACH"
  ],

  Colors: [
    "BLACK","WHITE","GRAY","SILVER","GOLD","RED","BLUE","GREEN","YELLOW","ORANGE",
    "PURPLE","PINK","BROWN","BEIGE","IVORY","TEAL","CYAN","NAVY","MAROON","OLIVE",
    "LIME","MINT","CORAL","PEACH","PLUM","INDIGO","VIOLET","AMBER","BRONZE","COPPER"
  ],

  Jobs: [
    "DOCTOR","NURSE","TEACHER","LAWYER","ENGINEER","ARCHITECT","DESIGNER","WRITER","EDITOR","REPORTER",
    "CHEF","BAKER","COOK","FARMER","GARDENER","DRIVER","PILOT","CAPTAIN","SAILOR","FISHER",
    "ACTOR","SINGER","DANCER","PAINTER","SCULPTOR","PHOTOGRAPHER","DIRECTOR","PRODUCER","CAMERAMAN","EDITORIAL"
  ],

  Sports: [
    "SOCCER","RUGBY","TENNIS","CRICKET","HOCKEY","BASEBALL","BASKETBALL","VOLLEY","HANDBALL","BADMINTON",
    "GOLF","BOXING","WRESTLING","KARATE","JUDO","TAEKWONDO","SKIING","SNOWBOARD","SURFING","SWIMMING",
    "RUNNING","CYCLING","ROWING","SAILING","CLIMBING","HIKING","SKATING","FENCING","ARCHERY","SHOOTING"
  ],

  Music: [
    "ROCK","POP","JAZZ","BLUES","SOUL","FUNK","DISCO","TECHNO","HOUSE","TRANCE",
    "HIPHOP","RAP","REGGAE","SKA","METAL","PUNK","GRUNGE","INDIE","FOLK","COUNTRY",
    "CLASSICAL","OPERA","CHORAL","SYMPHONY","ORCHESTRA","PIANO","GUITAR","DRUMS","BASS","VIOLIN"
  ],

  Movies: [
    "ACTION","DRAMA","COMEDY","HORROR","THRILLER","ROMANCE","WESTERN","FANTASY","SCIENCE","FICTION",
    "ANIMATION","DOCUMENTARY","MYSTERY","CRIME","NOIR","MUSICAL","BIOPIC","HISTORY","WAR","SPORTS",
    "SUPERHERO","ADVENTURE","EPIC","SHORT","SERIES","SEQUEL","PREQUEL","REMAKE","SPINOFF","CAMEO"
  ],

  Technology: [
    "COMPUTER","LAPTOP","TABLET","PHONE","SERVER","NETWORK","CLOUD","DATABASE","ALGORITHM","SOFTWARE",
    "HARDWARE","BROWSER","WEBSITE","APP","SECURITY","ENCRYPTION","PASSWORD","LOGIN","ACCOUNT","PROFILE",
    "BACKUP","STORAGE","MEMORY","PROCESSOR","GPU","CPU","FIRMWARE","PROTOCOL","API","FRAMEWORK"
  ],

  Nature: [
    "FOREST","DESERT","MOUNTAIN","RIVER","OCEAN","LAKE","VALLEY","HILL","CLIFF","CANYON",
    "ISLAND","BEACH","GLACIER","VOLCANO","WATERFALL","STREAM","SWAMP","JUNGLE","RAINFOREST","SAVANNA",
    "PLAINS","MEADOW","FIELD","GARDEN","PARK","RESERVE","DELTA","REEF","COAST","SHORE"
  ],

  Emotions: [
    "HAPPY","SAD","ANGRY","EXCITED","NERVOUS","CALM","RELAXED","STRESSED","ANXIOUS","PROUD",
    "ASHAMED","CONFIDENT","HOPEFUL","FEARFUL","CURIOUS","BORED","TIRED","ENERGETIC","LONELY","LOVED",
    "JEALOUS","GRATEFUL","CONTENT","FRUSTRATED","SURPRISED","CONFUSED","INSPIRED","MOTIVATED","DEPRESSED","OPTIMISTIC"
  ],

  Vehicles: [
    "CAR","TRUCK","BUS","TRAIN","TRAM","SUBWAY","SCOOTER","MOTORBIKE","BICYCLE","SKATEBOARD",
    "AIRPLANE","HELICOPTER","GLIDER","JET","BOAT","SHIP","FERRY","SUBMARINE","YACHT","CANOE",
    "KAYAK","RAFT","TANK","TRACTOR","CRANE","FORKLIFT","VAN","SUV","SEDAN","COUPE"
  ],

  Clothing: [
    "SHIRT","PANTS","JEANS","SHORTS","SKIRT","DRESS","JACKET","COAT","HOODIE","SWEATER",
    "SOCKS","SHOES","BOOTS","SANDALS","SNEAKERS","HAT","CAP","BEANIE","SCARF","GLOVES",
    "BELT","TIE","SUIT","BLAZER","VEST","PYJAMAS","UNDERWEAR","BRIEFS","BOXERS","BATHROBE"
  ],

  BodyParts: [
    "HEAD","BRAIN","EYES","EARS","NOSE","MOUTH","TEETH","TONGUE","NECK","SHOULDERS",
    "ARMS","ELBOW","WRIST","HANDS","FINGERS","CHEST","BACK","SPINE","WAIST","HIPS",
    "LEGS","KNEE","ANKLE","FEET","TOES","HEART","LUNGS","LIVER","STOMACH","MUSCLES"
  ],

  Weather: [
    "SUNNY","CLOUDY","RAINY","STORMY","WINDY","FOGGY","SNOWY","ICY","HUMID","DRY",
    "HOT","COLD","WARM","COOL","FREEZING","BOILING","BREEZY","OVERCAST","DROUGHT","FLOOD",
    "THUNDER","LIGHTNING","HAIL","BLIZZARD","CYCLONE","HURRICANE","TORNADO","MONSOON","RAINBOW","MIST"
  ],

  Space: [
    "PLANET","STAR","GALAXY","NEBULA","COMET","ASTEROID","METEOR","ORBIT","GRAVITY","VACUUM",
    "SATELLITE","ROCKET","SPACESHIP","ASTRONAUT","COSMONAUT","TELESCOPE","OBSERVATORY","CONSTELLATION","UNIVERSE","COSMOS",
    "MARS","VENUS","EARTH","JUPITER","SATURN","URANUS","NEPTUNE","PLUTO","ECLIPSE","SOLAR"
  ],

  Time: [
    "SECOND","MINUTE","HOUR","DAY","WEEK","MONTH","YEAR","DECADE","CENTURY","MILLENNIUM",
    "MORNING","NOON","AFTERNOON","EVENING","NIGHT","MIDNIGHT","DAWN","DUSK","TODAY","TOMORROW",
    "YESTERDAY","PAST","PRESENT","FUTURE","DEADLINE","SCHEDULE","CALENDAR","CLOCK","ALARM","TIMEZONE"
  ],

  Shapes: [
    "CIRCLE","SQUARE","TRIANGLE","RECTANGLE","OVAL","DIAMOND","STAR","HEART","CUBE","SPHERE",
    "CYLINDER","CONE","PYRAMID","HEXAGON","PENTAGON","OCTAGON","DECAGON","ELLIPSE","ARC","ANGLE",
    "LINE","CURVE","EDGE","FACE","VERTEX","PLANE","SOLID","FORM","PATTERN","SYMMETRY"
  ],

  Materials: [
    "WOOD","METAL","PLASTIC","GLASS","STONE","BRICK","CONCRETE","STEEL","IRON","COPPER",
    "ALUMINUM","SILVER","GOLD","FABRIC","COTTON","WOOL","SILK","LEATHER","RUBBER","CERAMIC",
    "PORCELAIN","CLAY","PAPER","CARDBOARD","FOAM","CARBON","FIBER","RESIN","LATEX","NYLON"
  ],

  Communication: [
    "MESSAGE","EMAIL","LETTER","CHAT","CALL","VIDEO","AUDIO","SIGNAL","BROADCAST","STREAM",
    "POST","COMMENT","REPLY","FORWARD","ATTACHMENT","SUBJECT","CONTENT","CHANNEL","NETWORK","CONTACT",
    "PROFILE","USERNAME","PASSWORD","LOGIN","LOGOUT","SESSION","NOTIFICATION","ALERT","STATUS","UPDATE"
  ],

  Education: [
    "SCHOOL","COLLEGE","UNIVERSITY","CLASS","LESSON","LECTURE","COURSE","SUBJECT","TOPIC","MODULE",
    "STUDENT","TEACHER","PROFESSOR","TUTOR","HOMEWORK","ASSIGNMENT","PROJECT","EXAM","TEST","QUIZ",
    "GRADE","SCORE","RESULT","DIPLOMA","DEGREE","CERTIFICATE","KNOWLEDGE","LEARNING","STUDY","REVISION"
  ],

  Finance: [
    "MONEY","CASH","COIN","BANK","ACCOUNT","SAVINGS","CREDIT","DEBIT","LOAN","INTEREST",
    "INVESTMENT","STOCK","BOND","ETF","FUND","MARKET","TRADE","PROFIT","LOSS","REVENUE",
    "SALARY","WAGE","INCOME","EXPENSE","BUDGET","TAX","INVOICE","PAYMENT","TRANSFER","BALANCE"
  ],

  Health: [
    "DOCTOR","PATIENT","CLINIC","HOSPITAL","MEDICINE","TABLET","VACCINE","THERAPY","TREATMENT","RECOVERY",
    "SYMPTOM","DIAGNOSIS","CONDITION","DISEASE","INFECTION","VIRUS","BACTERIA","IMMUNITY","FITNESS","EXERCISE",
    "DIET","NUTRITION","PROTEIN","VITAMIN","MINERAL","HYDRATION","SLEEP","REST","STRESS","WELLNESS"  
  ]
Transportation: [
  "CAR","TRUCK","BUS","TRAIN","TRAM","SUBWAY","SCOOTER","MOTORBIKE","BICYCLE","SKATEBOARD",
  "AIRPLANE","HELICOPTER","GLIDER","JET","BOAT","SHIP","FERRY","SUBMARINE","YACHT","CANOE",
  "KAYAK","RAFT","TANK","TRACTOR","CRANE","FORKLIFT","VAN","SUV","SEDAN","COUPE"
],

Clothing: [
  "SHIRT","PANTS","JEANS","SHORTS","SKIRT","DRESS","JACKET","COAT","HOODIE","SWEATER",
  "SOCKS","SHOES","BOOTS","SANDALS","SNEAKERS","HAT","CAP","BEANIE","SCARF","GLOVES",
  "BELT","TIE","SUIT","BLAZER","VEST","PYJAMAS","UNDERWEAR","BRIEFS","BOXERS","BATHROBE"
],

BodyParts: [
  "HEAD","BRAIN","EYES","EARS","NOSE","MOUTH","TEETH","TONGUE","NECK","SHOULDERS",
  "ARMS","ELBOW","WRIST","HANDS","FINGERS","CHEST","BACK","SPINE","WAIST","HIPS",
  "LEGS","KNEE","ANKLE","FEET","TOES","HEART","LUNGS","LIVER","STOMACH","MUSCLES"
],

Weather: [
  "SUNNY","CLOUDY","RAINY","STORMY","WINDY","FOGGY","SNOWY","ICY","HUMID","DRY",
  "HOT","COLD","WARM","COOL","FREEZING","BOILING","BREEZY","OVERCAST","DROUGHT","FLOOD",
  "THUNDER","LIGHTNING","HAIL","BLIZZARD","CYCLONE","HURRICANE","TORNADO","MONSOON","RAINBOW","MIST"
],

Space: [
  "PLANET","STAR","GALAXY","NEBULA","COMET","ASTEROID","METEOR","ORBIT","GRAVITY","VACUUM",
  "SATELLITE","ROCKET","SPACESHIP","ASTRONAUT","COSMONAUT","TELESCOPE","OBSERVATORY","CONSTELLATION","UNIVERSE","COSMOS",
  "MARS","VENUS","EARTH","JUPITER","SATURN","URANUS","NEPTUNE","PLUTO","ECLIPSE","SOLAR"
],

Time: [
  "SECOND","MINUTE","HOUR","DAY","WEEK","MONTH","YEAR","DECADE","CENTURY","MILLENNIUM",
  "MORNING","NOON","AFTERNOON","EVENING","NIGHT","MIDNIGHT","DAWN","DUSK","TODAY","TOMORROW",
  "YESTERDAY","PAST","PRESENT","FUTURE","DEADLINE","SCHEDULE","CALENDAR","CLOCK","ALARM","TIMEZONE"
],

Shapes: [
  "CIRCLE","SQUARE","TRIANGLE","RECTANGLE","OVAL","DIAMOND","STAR","HEART","CUBE","SPHERE",
  "CYLINDER","CONE","PYRAMID","HEXAGON","PENTAGON","OCTAGON","DECAGON","ELLIPSE","ARC","ANGLE",
  "LINE","CURVE","EDGE","FACE","VERTEX","PLANE","SOLID","FORM","PATTERN","SYMMETRY"
],

Materials: [
  "WOOD","METAL","PLASTIC","GLASS","STONE","BRICK","CONCRETE","STEEL","IRON","COPPER",
  "ALUMINUM","SILVER","GOLD","FABRIC","COTTON","WOOL","SILK","LEATHER","RUBBER","CERAMIC",
  "PORCELAIN","CLAY","PAPER","CARDBOARD","FOAM","CARBON","FIBER","RESIN","LATEX","NYLON"
],

Communication: [
  "MESSAGE","EMAIL","LETTER","CHAT","CALL","VIDEO","AUDIO","SIGNAL","BROADCAST","STREAM",
  "POST","COMMENT","REPLY","FORWARD","ATTACHMENT","SUBJECT","CONTENT","CHANNEL","NETWORK","CONTACT",
  "PROFILE","USERNAME","PASSWORD","LOGIN","LOGOUT","SESSION","NOTIFICATION","ALERT","STATUS","UPDATE"
],

Education: [
  "SCHOOL","COLLEGE","UNIVERSITY","CLASS","LESSON","LECTURE","COURSE","SUBJECT","TOPIC","MODULE",
  "STUDENT","TEACHER","PROFESSOR","TUTOR","HOMEWORK","ASSIGNMENT","PROJECT","EXAM","TEST","QUIZ",
  "GRADE","SCORE","RESULT","DIPLOMA","DEGREE","CERTIFICATE","KNOWLEDGE","LEARNING","STUDY","REVISION"
],

Finance: [
  "MONEY","CASH","COIN","BANK","ACCOUNT","SAVINGS","CREDIT","DEBIT","LOAN","INTEREST",
  "INVESTMENT","STOCK","BOND","ETF","FUND","MARKET","TRADE","PROFIT","LOSS","REVENUE",
  "SALARY","WAGE","INCOME","EXPENSE","BUDGET","TAX","INVOICE","PAYMENT","TRANSFER","BALANCE"
],

Health: [
  "DOCTOR","PATIENT","CLINIC","HOSPITAL","MEDICINE","TABLET","VACCINE","THERAPY","TREATMENT","RECOVERY",
  "SYMPTOM","DIAGNOSIS","CONDITION","DISEASE","INFECTION","VIRUS","BACTERIA","IMMUNITY","FITNESS","EXERCISE",
  "DIET","NUTRITION","PROTEIN","VITAMIN","MINERAL","HYDRATION","SLEEP","REST","STRESS","WELLNESS"
],

Furniture: [
  "SOFA","CHAIR","TABLE","DESK","CABINET","SHELF","BED","MATTRESS","LAMP","BOOKCASE",
  "STOOL","COUCH","COFFEE","SIDE","NIGHTSTAND","DRAWER","DRESSER","BENCH","WARDROBE","ARMCHAIR",
  "OTTOMAN","CUPBOARD","TVSTAND","RUG","CARPET","MIRROR","PICTURE","FRAME","SHELVES","HANGER"
],

Tools: [
  "HAMMER","SCREWDRIVER","WRENCH","PLIERS","SAW","DRILL","NAILS","SCREWS","BOLT","NUT",
  "LEVEL","CHISEL","SANDER","TAPE","MEASURE","KNIFE","CUTTER","AXE","MOP","BROOM",
  "SHOVEL","HOE","RAKE","LADDER","PAINT","BRUSH","ROLLER","GLUE","CLAMP","VISE"
],

Instruments: [
  "GUITAR","PIANO","DRUMS","FLUTE","VIOLIN","TRUMPET","SAXOPHONE","TROMBONE","HARP","CELLO",
  "BASS","CLARINET","OBOE","BAGPIPE","ACCORDION","MANDOLIN","BANJO","UKULELE","TUBA","SITAR",
  "XYLAPHONE","MARIMBA","TAMBOURINE","CONGA","DJEMBE","SYNTH","KEYBOARD","ORGAN","GLOCKENSPIEL","PANFLUTE"
],

VehiclesWater: [
  "BOAT","SHIP","YACHT","FERRY","SUBMARINE","KAYAK","CANOE","RAFT","SPEEDBOAT","SCHOONER",
  "CATAMARAN","CRUISE","VESSEL","STEAMER","SAILBOAT","JUNK","BARGE","TUG","FISHING","FERRYBOAT",
  "DINGHY","ROWBOAT","PADDLE","KETCH","TRAWLER","YACHTING","MOTORBOAT","FRIGATE","CORVETTE","CLIPPER"
],

VehiclesAir: [
  "AIRPLANE","JET","GLIDER","HELICOPTER","BALLOON","PARACHUTE","DRONE","BIPLANE","TRICOPTER","QUADCOPTER",
  "SPACESHIP","ROCKET","MOTHERSHIP","SPACECRAFT","CARRIER","FIGHTER","BOMBER","GUNSHIP","SEAPLANE","FLOATPLANE",
  "ULTRALIGHT","GYROCOPTER","DIRIGIBLE","ZEPLIN","BALLONET","HANGGLIDER","PARAGLIDER","WINGLET","AEROBATIC","STOL"
],

Politics: [
  "PRESIDENT","PRIME","MINISTER","SENATOR","GOVERNOR","MAYOR","COUNCIL","CABINET","PARLIAMENT","CONGRESS",
  "VOTE","ELECTION","DEBATE","LAW","BILL","ACT","CONSTITUTION","PARTY","LEADER","OPPOSITION",
  "DIPLOMAT","AMBASSADOR","EMBASSY","TREATY","NEGOTIATION","POLICY","REFORM","CAMPAIGN","COALITION","LEGISLATION"
],

Science: [
  "PHYSICS","CHEMISTRY","BIOLOGY","ASTRONOMY","GEOLOGY","ECOLOGY","GENETICS","MICROBIOLOGY","NEUROSCIENCE","BOTANY",
  "ZOOLOGY","MATHEMATICS","STATISTICS","ASTROPHYSICS","METEOROLOGY","ANATOMY","PHARMACOLOGY","BIOCHEMISTRY","ENGINEERING","TECHNOLOGY",
  "ROBOTICS","QUANTUM","RELATIVITY","OPTICS","THERMODYNAMICS","ELECTRICITY","MAGNETISM","ENERGY","GRAVITY","FORCE"
],

History: [
  "WAR","REVOLUTION","EMPIRE","KINGDOM","DYNASTY","MONARCH","PRESIDENT","COLONY","SETTLEMENT","DISCOVERY",
  "CONQUEST","BATTLE","TREATY","ALLIANCE","REIGN","ERA","PERIOD","CENTURY","MILLENNIUM","AGE",
  "CIVILIZATION","CULTURE","TRADITION","HERITAGE","MONUMENT","ARCHAEOLOGY","ARTIFACT","HISTORY","LEGEND","MYTH"
],

Literature: [
  "NOVEL","POEM","POETRY","STORY","FICTION","NONFICTION","ESSAY","DRAMA","TRAGEDY","COMEDY",
  "PLAY","NARRATIVE","CHAPTER","VERSE","LINE","PROSE","SHORTSTORY","BIOGRAPHY","AUTOBIOGRAPHY","FABLE",
  "MYTH","LEGEND","EPIC","SONNET","HAIKU","PARABLE","SCRIPT","SCREENPLAY","ROMANCE","MYSTERY"
],

Languages: [
  "ENGLISH","FRENCH","SPANISH","GERMAN","ITALIAN","PORTUGUESE","RUSSIAN","CHINESE","JAPANESE","KOREAN",
  "ARABIC","HINDI","BENGALI","URDU","PERSIAN","TURKISH","SWEDISH","DUTCH","NORWEGIAN","FINNISH",
  "POLISH","CZECH","SLOVAK","GREEK","HEBREW","THAI","VIETNAMESE","LAO","TAGALOG","MALAY"
],

Art: [
  "PAINTING","SCULPTURE","DRAWING","PHOTOGRAPHY","MOSAIC","FRESCO","CERAMICS","CALLIGRAPHY","GRAFFITI","ETCHING",
  "COLLAGE","ILLUSTRATION","ENGRAVING","CARVING","PRINTMAKING","TEXTILE","WEAVING","KNITTING","CERAMIC","WATERCOLOR",
  "OIL","ACRYLIC","INK","PASTEL","CHARCOAL","GRAPHITE","STENCIL","DIGITAL","MURAL","SKETCH"
],

NaturePlants: [
  "TREE","FLOWER","GRASS","BUSH","FERN","MOSS","CACTUS","VINE","SHRUB","LEAF",
  "ROOT","SEED","FRUIT","VEGETABLE","HERB","SPICE","POD","BULB","BRANCH","STEM",
  "FLOWERBED","GARDEN","FOREST","JUNGLE","RAINFOREST","MEADOW","PLAINS","SAVANNA","PARK","RESERVE"
],

Gems: [
  "DIAMOND","RUBY","SAPPHIRE","EMERALD","OPAL","PEARL","TOPAZ","AMETHYST","AQUAMARINE","CITRINE",
  "GARNET","TURQUOISE","ONYX","JADE","PERIDOT","QUARTZ","TANZANITE","MOONSTONE","SPINEL","CHALCEDONY",
  "BERYL","CHRYSOLITE","CORUNDUM","LABRADORITE","AGATE","LAPIS","MALACHITE","OBSIDIAN","RUBELLITE","SUGILITE"
],

FurnitureRoom: [
  "LIVINGROOM","BEDROOM","KITCHEN","BATHROOM","DININGROOM","OFFICE","STUDY","HALLWAY","GARAGE","BALCONY",
  "LOUNGE","ATTIC","BASEMENT","SUNROOM","LIBRARY","PLAYROOM","STORAGE","PANTRY","CLOSET","MUDROOM",
  "PORCH","DECK","GARDEN","PATIO","VERANDA","LOBBY","STUDIO","CONSERVATORY","GYM","THEATER"
]
