const THEMES = {
    "Animals": ["Dog", "Cat", "Elephant", "Tiger", "Lion", "Panda", "Koala", "Giraffe", "Zebra", "Bear",
                "Fox", "Wolf", "Rabbit", "Deer", "Horse", "Monkey", "Kangaroo", "Penguin", "Dolphin", "Shark",
                "Whale", "Otter", "Squirrel", "Raccoon", "Camel", "Sheep", "Goat", "Chicken", "Duck", "Goose"],
    "Fruits": ["Apple", "Banana", "Orange", "Grape", "Mango", "Strawberry", "Blueberry", "Pineapple", "Peach", "Pear",
               "Watermelon", "Kiwi", "Lemon", "Lime", "Cherry", "Papaya", "Plum", "Apricot", "Raspberry", "Coconut",
               "Grapefruit", "Fig", "Pomegranate", "Avocado", "Cantaloupe", "Blackberry", "Dragonfruit", "Date", "Guava", "Passionfruit"],
    "Colors": ["Red", "Blue", "Green", "Yellow", "Purple", "Orange", "Pink", "Brown", "Black", "White",
               "Gray", "Cyan", "Magenta", "Teal", "Violet", "Indigo", "Maroon", "Olive", "Gold", "Silver",
               "Beige", "Turquoise", "Lavender", "Mint", "Coral", "Navy", "Peach", "Chocolate", "Tan", "Cream"],
    "Countries": ["USA", "Canada", "France", "Germany", "Italy", "Spain", "Japan", "China", "Brazil", "Mexico",
                  "Australia", "India", "Russia", "UK", "Sweden", "Norway", "Netherlands", "Belgium", "Switzerland", "Argentina",
                  "Chile", "Egypt", "Greece", "Thailand", "Vietnam", "SouthKorea", "NewZealand", "Ireland", "Portugal", "Poland"],
    "Sports": ["Soccer", "Basketball", "Tennis", "Baseball", "Golf", "Cricket", "Rugby", "Volleyball", "Hockey", "Boxing",
               "Swimming", "Running", "Cycling", "Skiing", "Skating", "Surfing", "Karate", "Wrestling", "Gymnastics", "Bowling",
               "Sailing", "Archery", "Fencing", "Badminton", "TableTennis", "Snowboarding", "Climbing", "Weightlifting", "Kayaking", "Diving"],
    "Foods": ["Pizza", "Burger", "Pasta", "Sushi", "Taco", "Salad", "Steak", "Sandwich", "Soup", "Fries",
              "Chocolate", "IceCream", "Bread", "Rice", "Cheese", "Egg", "Milk", "Yogurt", "ApplePie", "Donut",
              "Bagel", "Pancake", "Waffle", "Cookie", "Muffin", "Cereal", "Noodles", "HotDog", "Chili", "Pie"],
    "Emotions": ["Happy", "Sad", "Angry", "Excited", "Bored", "Confused", "Surprised", "Scared", "Calm", "Joyful",
                 "Anxious", "Proud", "Shy", "Nervous", "Curious", "Frustrated", "Relaxed", "Energetic", "Lonely", "Grateful",
                 "Jealous", "Embarrassed", "Hopeful", "Guilty", "Optimistic", "Confident", "Tired", "Disappointed", "Afraid", "Content"],
    "Objects": ["Chair", "Table", "Lamp", "Phone", "Laptop", "Book", "Pen", "Notebook", "Bag", "Bottle",
                "Key", "Wallet", "Watch", "Glasses", "Shoes", "Hat", "Umbrella", "Door", "Window", "Mirror",
                "Brush", "Camera", "Speaker", "Headphones", "Television", "Sofa", "Pillow", "Rug", "Clock", "Fan"],
    "Professions": ["Doctor", "Engineer", "Teacher", "Nurse", "Pilot", "Chef", "Artist", "Lawyer", "Farmer", "Driver",
                    "Firefighter", "Police", "Scientist", "Writer", "Musician", "Designer", "Actor", "Singer", "Dancer", "Programmer",
                    "Photographer", "Mechanic", "Electrician", "Plumber", "Architect", "Journalist", "Baker", "Tailor", "Coach", "Soldier"]
};